### ISSUE TITLE
Create individual pantries per user

### ISSUE THREAD

**Issue by QwertycowMoo** [Pan-Lang/backend#12]
Creating new Collections for the MongoDB so that we can support multiple pantries if need be

**Comment by renzol2** [comment]
Now that we've verified auth works on frontend, we should create individual pantries for each account. Since we've switched to Firebase, we should make separate collections in Firestore for each account. Every account has a unique email so we should probably use that as an ID?

**Comment by QwertycowMoo** [comment]
I think the way that we can do this is to create an endpoint function on the API that you would send the unique ID and the API would create a new collection. Remember that the API would not be doing any authentication, so we would have to send the user ID along with the request to get the correct collection.

**Comment by QwertycowMoo** [comment]
Fixed with #22
